node:
  host: ${NODE_HOST}
  port: ${NODE_PORT}
  external: ${NODE_EXTERNAL_IP}

logging:
  level: ${LOGGING_LEVEL}

contracts:
  linkCollectionAddress : ${LINK_COLLECTION_ADDRESS}

validator:
  validatorKey: ${VALIDATOR_KEY}
  authenticationMode: ${AUTHENTICATION_MODE}
